apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Build the new PHP 7.2 s2i image.
  name: php-s2i-72-graphviz
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'php-s2i-72-graphviz:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /7.2
    git:
      uri: 'https://github.com/pittar/s2i-php-container.git'
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
