apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: appname
    name: appname-build
  name: appname-s2i-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: appname:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-8:1.3
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
